### ISSUE TITLE
 Error: dlopen(/Users/dongguotao/byteball/node_modules/sqlite3/lib/binding/node-webkit-v0.29.2-darwin-x64/node_sqlite3.node, 1): no suitable image found.

### ISSUE THREAD

**Issue by Dgtlinux** [byteball/byteball#307]
node version:5.12.0
npm version:3.8.6

when I run like this:

localhost:byteball dongguotao$ ../nwjs-v0.29.2-osx-x64/nwjs.app/Contents/MacOS/nwjs .

the output is:

module.js:721
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/dongguotao/byteball/node_modules/sqlite3/lib/binding/node-webkit-v0.29.2-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/Users/dongguotao/byteball/node_modules/sqlite3/lib/binding/node-webkit-v0.29.2-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1605632 which is past end of file 151552
	/Users/dongguotao/byteball/node_modules/sqlite3/lib/binding/node-webkit-v0.29.2-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1605632 which is past end of file 151552
    at Object.Module._extensions..node (module.js:721:18)
    at Module.load (module.js:586:32)
    at tryModuleLoad (module.js:526:12)
    at Function.Module._load (module.js:518:3)
    at Module.require (module.js:618:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dongguotao/byteball/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:674:30)
    at Object.Module._extensions..js (module.js:691:10)
    at Module.load (module.js:586:32)

who can help me!

**Comment by tonyofbyteball** [comment]
looks like you are using node 5.12.0 with nwjs-v0.29.2, which are not compatible.  nwjs should be 0.14.7
