### ISSUE TITLE
Cannot find module '/home/thing/byteball/byteball/node_modules/byteballcore/node_modules/sqlite3/lib/binding/node-webkit-v0.14.7-linux-x64/node_sqlite3.node'

### ISSUE THREAD

**Issue by Yangk030208** [byteball/byteball#312]
After installing and compiling the document, I run  commond  “ nw  . ” ,     This error occurred. Who can help me ?  thanks .

`module.js:365
    throw err;
    ^
Error: Cannot find module 
 '/home/thing/byteball/byteball/node_modules/byteballcore/node_modules/sqlite3/lib/binding/node-webkit-v0.14.7-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:363:15)
    at Function.Module._load (module.js:309:25)
    at Module.require (module.js:391:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/thing/byteball/byteball/node_modules/byteballcore/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:437:34)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:381:32)
    at Function.Module._load (module.js:338:12)
    at Module.require (module.js:391:17)
`

**Comment by Yangk030208** [comment]
I have  installed SQLite3 and this npm  package .

**Comment by xJeneKx** [comment]
"After first run, you'll likely encounter runtime error complaining about node_sqlite3.node not being found, copy the file from the neighboring directory to where the program tries to find it, and run again. (e.g. from byteball/node_modules/sqlite3/lib/binding/node-v47-darwin-x64 to byteball/node_modules/sqlite3/lib/binding/node-webkit-v0.14.7-darwin-x64)"
