### ISSUE TITLE
SEGFAULT under Linux

### ISSUE THREAD

**Issue by stevesbrain** [byteball/byteball#338]
Hey guys, I'm getting the following Segfault under Arch Linux which previously (and still) runs 2.2 version just fine:

```bash
(gdb) run
Starting program: /usr/bin/byteball
[Thread debugging using libthread_db enabled]
Using host libthread_db library /usr/lib/libthread_db.so.1.
[New Thread 0x7fffe45cc700 (LWP 5359)]
LaunchProcess: failed to execvp:
/usr/share/byteball/nacl_helper
[5360:5360:0629/204632:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)

Thread 1 byteball received signal SIGSEGV, Segmentation fault.
0x00007fffe9dd2d60 in pango_fc_font_get_glyph () from /usr/lib/libpangoft2-1.0.so.0
(gdb) bt
#0  0x00007fffe9dd2d60 in pango_fc_font_get_glyph () at /usr/lib/libpangoft2-1.0.so.0
#1  0x00007fffe9dd2db7 in  () at /usr/lib/libpangoft2-1.0.so.0
#2  0x00005555555813d4 in hb_font_funcs_set_glyph_extents_func ()
#3  0x0000000000000000 in  ()
(gdb)
```

Tried removing + reinstalling relevant pango/etc packages, and clearing font cache etc - no avail though. Any clues? New dependencies introduced or something?

**Comment by Huii** [comment]
Same problem here on Debian GNU/Linux. Downloading the latest byteball release and attempting to start it only results in a segmentation fault.

**Comment by FredericS2018** [comment]
+1

**Comment by stevesbrain** [comment]
Still happening in 2.4.0 and 2.4.1 :(

**Comment by nicomanso** [comment]
Same output from Debian GNU/Linux:

```Thread 1 "Byteball" received signal SIGSEGV, Segmentation fault.
0x00007fffeb5df250 in pango_fc_font_get_glyph () from /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
(gdb) bt
#0  0x00007fffeb5df250 in pango_fc_font_get_glyph () at /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
#1  0x00007fffeb5e33c6 in  () at /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
#2  0x00005555555813d4 in hb_font_funcs_set_glyph_extents_func ()
#3  0x0000000000000000 in  ()
(gdb) 
```

Any workaround?

**Comment by stevesbrain** [comment]
@nicomanso Unfortunately none that I've seen. Would seem Linux platform isn't particularly high on Tony's list at this point in time.

**Comment by nicomanso** [comment]
It is working now on debian testing.

**Comment by stevesbrain** [comment]
Can confirm working on Arch now too!
